# -*- coding: utf-8 -*-
"""Cars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100R9ncUbT1LbzqVyCRoEBqmYh0zc5VGc

# Check Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df = pd.read_excel("/content/cars.xlsx")
df

df.info()

df.dtypes

df.duplicated().sum()

df.isnull().sum()

df.describe()

df.columns = df.columns.str.strip()

"""# Bussines Question

1️ ما هي الفئة الاكثر عددا من المنتجات
"""

counts = df['الفئة'].value_counts().reset_index()
counts.columns = ['الفئة', 'العدد']
counts = counts.astype(str)
for col in counts.columns:
    max_len = counts[col].str.len().max() + 4
    counts[col] = counts[col].apply(lambda x: x.center(max_len))
headers = [col.center(counts[col].str.len().max()) for col in counts.columns]
print(tabulate(counts, headers=headers, tablefmt="fancy_grid", showindex=False))

"""2️⃣ ما هو متوسط السعر لكل فئة من الفئات؟"""

from tabulate import tabulate
avg_price_by_cat = df.groupby('الفئة', as_index=False)['السعر'].mean().sort_values('السعر', ascending=False)
avg_price_by_cat = avg_price_by_cat.astype(str)
for col in avg_price_by_cat.columns:
    max_len = avg_price_by_cat[col].str.len().max()
    avg_price_by_cat[col] = avg_price_by_cat[col].apply(lambda x: x.center(max_len))
print(tabulate(
    avg_price_by_cat,
    headers=[col.center(len(col)) for col in avg_price_by_cat.columns],
    tablefmt='fancy_grid',
    showindex=False
))

"""3️⃣ ما هي أغلى 5 سيارات ؟"""

from tabulate import tabulate
print(tabulate(
    top_unique,
    headers=top_unique.columns,
    tablefmt='fancy_grid',
    showindex=False,
    colalign=("center", "center", "center")
))

"""3️⃣ ما هو متوسط سعر الوان السيارات من الاغلي الي الارخص؟"""

color_price = df.groupby('اللون')['السعر'].mean().sort_values(ascending=False).reset_index()
color_price.columns = ['اللون', 'متوسط السعر']

color_price = color_price.astype(str)
for col in color_price.columns:
    max_len = color_price[col].str.len().max() + 4
    color_price[col] = color_price[col].apply(lambda x: x.center(max_len))
headers = [col.center(color_price[col].str.len().max()) for col in color_price.columns]

print(tabulate(color_price, headers=headers, tablefmt="fancy_grid", showindex=False))

"""5️⃣ ما هي اقل اسعار السيارات في كل فئة"""

min_price = df.loc[df.groupby('الفئة')['السعر'].idxmin()][['السعر','الاسم','الفئة']].copy()
min_price['السعر'] = min_price['السعر'].astype(int)
table_rows = min_price.astype(str).values.tolist()
headers = ['الفئة', 'الاسم', 'السعر']
print(tabulate(
    table_rows,
    headers=headers,
    tablefmt='fancy_grid',
    showindex=False,
    colalign=('center','center','center')
))

"""6️⃣ نطاق الأسعار (Min – Max) لكل فئة"""

range_price = df.groupby("الفئة")["السعر"].agg(["min", "max"]).reset_index()
range_price.columns = ["الفئة", "أرخص سعر", "أغلى سعر"]
print(tabulate(range_price, headers=range_price.columns, tablefmt="fancy_grid", showindex=False))

"""7️⃣ اكثر الالوان انتشارا؟"""

color_count = df["اللون"].value_counts().reset_index()
color_count.columns = ["اللون", "عدد السيارات"]
print(tabulate(color_count, headers=color_count.columns, tablefmt="fancy_grid", showindex=False))

""" 8️⃣ الألوان الأكثر انتشارًا لكل فئة؟"""

color_by_cat = df.groupby(["الفئة","اللون"]).size().reset_index(name="عدد السيارات")
print(tabulate(color_by_cat, headers=["الفئة", "اللون", "عدد السيارات"], tablefmt="fancy_grid", showindex=False))

"""9️⃣ما هي الفئة التي تحتوي على أغلى منتج مقارنةً بمتوسط أسعارها؟"""

max_price_per_cat = df.groupby("الفئة")["السعر"].max().reset_index(name="اغلى_منتج")
avg_price_per_cat = df.groupby("الفئة")["السعر"].mean().reset_index(name="متوسط_السعر")

merged = pd.merge(max_price_per_cat, avg_price_per_cat, on="الفئة")
merged["التميز"] = (merged["اغلى_منتج"] / merged["متوسط_السعر"]).round(2)

table_rows = merged.astype(str).values.tolist()
headers = ["الفئة", "أغلى منتج", "متوسط الفئة", "مؤشر التميز"]

print(tabulate(
    table_rows,
    headers=headers,
    tablefmt="fancy_grid",
    showindex=False,
    colalign=("center","center","center","center")
))

"""🔟 ما هي الفئة التي تتميز بأكبر تنوع سعري داخلها؟"""

price_range_per_category = df.groupby("الفئة")["السعر"].agg(["min", "max"])
price_range_per_category["مدى الأسعار"] = price_range_per_category["max"] - price_range_per_category["min"]
price_range_per_category = price_range_per_category.reset_index().sort_values("مدى الأسعار", ascending=False)

table_rows = price_range_per_category.astype(str).values.tolist()
headers = ["الفئة", "أقل سعر", "أعلى سعر", "مدى الأسعار"]

print(tabulate(
    table_rows,
    headers=headers,
    tablefmt="fancy_grid",
    showindex=False,
    colalign=("center","center","center","center")
))

"""# Visuals"""

import plotly.express as px

category_counts = df["الفئة"].value_counts().reset_index()
category_counts.columns = ["الفئة", "عدد المنتجات"]

fig = px.bar(
    category_counts,
    x="الفئة", y="عدد المنتجات",
    title="📊 عدد المنتجات في كل فئة",
    color="عدد المنتجات", color_continuous_scale="Viridis"
)
fig.update_layout(title_font=dict(size=20), xaxis_title="الفئة", yaxis_title="عدد المنتجات")
fig.show()

fig = px.histogram(
    df, x="السعر", nbins=20,
    title="💰 توزيع الأسعار",
    color_discrete_sequence=["#1f77b4"]
)
fig.update_layout(title_font=dict(size=20), xaxis_title="السعر", yaxis_title="عدد المنتجات")
fig.show()

avg_price = df.groupby("الفئة", as_index=False)["السعر"].mean()

fig = px.bar(
    avg_price,
    x="الفئة", y="السعر",
    title="📈 متوسط السعر لكل فئة",
    color="السعر", color_continuous_scale="Plasma"
)
fig.update_layout(title_font=dict(size=20), xaxis_title="الفئة", yaxis_title="متوسط السعر")
fig.show()

color_counts = df["اللون"].value_counts().reset_index()
color_counts.columns = ["اللون", "عدد المنتجات"]

fig = px.bar(
    color_counts.head(10),
    x="اللون", y="عدد المنتجات",
    title="🎨 الألوان الأكثر تكرارًا",
    color="عدد المنتجات", color_continuous_scale="Turbo"
)
fig.update_layout(title_font=dict(size=20), xaxis_title="اللون", yaxis_title="عدد المنتجات")
fig.show()

fig = px.box(
    df, x="اللون", y="السعر", color="اللون",
    title="📦 توزيع الأسعار حسب اللون"
)
fig.update_layout(title_font=dict(size=20), xaxis_title="اللون", yaxis_title="السعر")
fig.show()

fig = px.box(
    df,
    y="السعر",
    title="💰 توزيع الأسعار بين المنتجات",
    points="all"
)
fig.update_layout(title_font=dict(size=22), yaxis_title="السعر")
fig.show()

fig = px.pie(
    category_counts,
    names="الفئة", values="عدد المنتجات",
    title="📊 توزيع نسبة المنتجات حسب الفئة",
    hole=0.4
)
fig.update_traces(textinfo="percent+label")
fig.show()

avg_color_price = df.groupby("اللون")["السعر"].mean().reset_index()

fig = px.treemap(
    avg_color_price,
    path=["اللون"], values="السعر",
    title="🌳 متوسط السعر حسب اللون"
)
fig.show()